const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (s) => ipcRenderer.invoke('settings:save', s),
  validateSettings: (s) => ipcRenderer.invoke('settings:validate', s),
  setTint: (v) => ipcRenderer.invoke('settings:set-tint', v),
  setLangTarget: (v) => ipcRenderer.invoke('settings:set-lang-target', v),
  setDeepMode: (v) => ipcRenderer.invoke('settings:set-deep-mode', v),
  setClipWatch: (v) => ipcRenderer.invoke('settings:set-clip-watch', v),
  setHotkey: (v) => ipcRenderer.invoke('settings:set-hotkey', v),
  getDataDir: () => ipcRenderer.invoke('settings:get-data-dir'),
  setDataDir: (mode) => ipcRenderer.invoke('settings:set-data-dir', mode),
  onClipboardChanged: (cb) => ipcRenderer.on('clipboard:changed', (_e, payload) => cb(payload)),
  translate: (p) => ipcRenderer.invoke('translate:run', p),
  cancelTranslate: (seq) => ipcRenderer.invoke('translate:cancel', seq),
  onTranslateDelta: (cb) => ipcRenderer.on('translate:delta', (_e, payload) => cb(payload)),
  listHistory: () => ipcRenderer.invoke('history:list'),
  deleteHistory: (id) => ipcRenderer.invoke('history:delete', id),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  getTerms: () => ipcRenderer.invoke('terms:get'),
  setTermsConfig: (cfg) => ipcRenderer.invoke('terms:set-config', cfg),
  addTerm: (p) => ipcRenderer.invoke('terms:add', p),
  removeTerm: (id) => ipcRenderer.invoke('terms:remove', id),
  toggleTerm: (p) => ipcRenderer.invoke('terms:toggle', p),
  importTermsCsv: (text) => ipcRenderer.invoke('terms:import-csv', text),
  restoreTermsPreset: () => ipcRenderer.invoke('terms:restore-preset'),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close'),
  setPin: (on) => ipcRenderer.invoke('window:pin', on),
  copyText: (t) => ipcRenderer.invoke('clipboard:write', t),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
});
